#!/bin/bash
result=$(echo "$WATER$STIR" | tr -d '.' | tr -cd '[[:alnum:]]' | tr -d 'a-z' | tr -d 'A-Z' | tr -d '[:digit:]' | tr -d '_' | tr -d '-' | tr -d '=' | tr -d '+' | tr -d '/' | tr -d '\\' | tr -d '*' | tr -d '%' | tr -d '^' | tr -d '!' | tr -d '&')
printf "%x\n" "$((16#${result}))"
